language: python
matrix:
  include:
    - python: "2.7"
      env: SYNTAX=false
    - python: "3.5"
      env: SYNTAX=false
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - if [ "$SYNTAX" == true ]; then exec tox -e syntax; fi
  - tox -e py$(sed 's/\.//g' <<<${TRAVIS_PYTHON_VERSION})-integration
